### PR TITLE
Miscellaneous Code Cleanup

### PR DESCRIPTION
**Pull request by istx25**
Hello @cabotmoose,

I am using plaid-swift in an app I'm building for a client. There were a few things that were bothering me (mostly code-style related), so I fixed them. I also have a few other improvements that I will implement/submit a PR for in the near future.

Cheers! :dancer:

### CODE REVIEW

**Comment by AndrewSB** [comment]
+1

**Comment by istx25** [comment]
@AndrewSB Checkout my new framework. It's a WIP. http://www.github.com/istx25/plaidster.

**Comment by AndrewSB** [comment]
It looks great! Is there Carthage support yet?

**Comment by istx25** [comment]
Yes

**Comment by AndrewSB** [comment]
🎉

**Comment by istx25** [comment]
Closing this since the owner has not addressed the PR since I opened it.

**Pull request closed without merging**
